# Generated by Django 3.1.6 on 2021-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0002_alter_carausel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
