# Generated by Django 3.1.6 on 2021-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0003_auto_20210503_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=150)),
                ('hoverText', models.CharField(max_length=150)),
                ('origin', models.URLField()),
                ('imgCert', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=150)),
                ('hoverText', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('siglas', models.CharField(max_length=30)),
                ('sizes', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('freezing', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.AlterModelOptions(
            name='carausel',
            options={'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
    ]
