# Generated by Django 3.1.6 on 2021-05-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0004_auto_20210507_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carausel',
            options={'verbose_name': 'foto carousel', 'verbose_name_plural': 'fotos carousel'},
        ),
    ]
