# Generated by Django 3.2 on 2021-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0006_carausel_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
