# Generated by Django 3.2 on 2021-05-21 02:54

from django.db import migrations, models
import django_countries.fields
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0007_alter_carausel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=12)),
                ('Pais', django_countries.fields.CountryField(max_length=2)),
                ('Mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
