# Generated by Django 3.2 on 2021-05-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0008_contacto_mapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mapa',
        ),
    ]
