# Generated by Django 3.1.6 on 2021-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0009_delete_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='docCert',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
