# Generated by Django 3.1.6 on 2021-05-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0010_certificado_doccert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
