# Generated by Django 3.1.6 on 2021-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0011_auto_20210521_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('thumbnail', models.CharField(max_length=150)),
                ('filepath', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'archivo multimedia',
                'verbose_name_plural': 'archivos multimedia',
            },
        ),
    ]
