# Generated by Django 3.1.6 on 2021-05-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0012_archivomultimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='section',
            field=models.CharField(choices=[('INI', 'inicio'), ('NOS', 'inicio')], default='INI', max_length=3),
        ),
    ]
