# Generated by Django 3.1.6 on 2021-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0013_auto_20210524_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
