# Generated by Django 3.1.6 on 2021-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0015_auto_20210524_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carausel',
            old_name='image',
            new_name='imagenWeb',
        ),
        migrations.AddField(
            model_name='carausel',
            name='imagenMov',
            field=models.CharField(default='', max_length=150),
        ),
    ]
