# Generated by Django 3.1.6 on 2021-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0016_auto_20210524_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Telefono',
            field=models.CharField(max_length=13),
        ),
    ]
