# Generated by Django 3.1.6 on 2021-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0017_auto_20210531_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('siglas', models.CharField(max_length=30)),
                ('sizes', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('freezing', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=models.CharField(max_length=30))),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
