# Generated by Django 3.1.6 on 2021-06-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0018_productocarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCarousel',
        ),
    ]
