# Generated by Django 3.1.6 on 2021-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaron', '0019_delete_productocarousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carausel',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='carausel',
            name='title_cn',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='carausel',
            name='title_en',
            field=models.CharField(default='', max_length=500),
        ),
    ]
